### ISSUE TITLE
Messages written to the report using a scenario.write() from @AfterStep are not fully visible

### ISSUE THREAD

**Issue by josepj** [trivago/cluecumber#115]
*Cluecumber report v1.6.2*
*Cucumber v4.2.0*

Thanks for this great reporting tool @laxersaz. Not sure whether I am doing something wrong, but messages written to the report using a scenario.write() from AfterStep are not fully visible. 

I tried the following from AfterStep:
```
scenario.write("### Log message 1");
scenario.write("### Log message 2");
scenario.write("### Log message 3");
```
And the messages appear in the report like this:

![logsafterstep](https://user-images.githubusercontent.com/9464895/50801526-c4fa7780-12aa-11e9-86f9-16cc14218613.png)

**Comment by laxersaz** [comment]
I just noticed this behavior too while working on the current release. I will tackle this now and include it in the upcoming 1.6.3
