### ISSUE TITLE
Extend cluecumber report to provide capabilities info

### ISSUE THREAD

**Issue by abhishek8908** [trivago/cluecumber#148]
I have my features structure
**src/test/resource/features/admin-tool/loginPage.feature**
**src/test/resource/features/admin-tool/Users.feature**

where dir admin-tool is my **Capability/Application**

Is it possible to get the summary of the test cases passed failed for the **admin-tool**

Maybe a possible solution is to get some info from the report.json

**"uri":"file:src/test/resource/features/admin-tool/loginPage.feature"**

**Comment by laxersaz** [comment]
Hi @abhishek8908 ,
Do your features related to admin-tool have the feature name "admin-tool" as well? Because in the Cluecumber pages you can always filter by any string - this also filters the feature names.
Maybe I don't understand your case correctly...

**Comment by abhishek8908** [comment]
Thanks, maybe this request is more inspired by serenity-cucumber reports where the framework treats every directory where the feature files reside as kind of capability/component/of the application under test. 

Which allows you to get an overview of your components tests.

![image](https://user-images.githubusercontent.com/22909519/55294391-feea9e00-5401-11e9-973e-2cc8b1d94267.png)

I not sure if this makes any sense, but thanks anyway :)

**Comment by laxersaz** [comment]
Interesting approach for sure. I will keep this in mind for the next version of Cluecumber.

**Comment by laxersaz** [comment]
Closing this since #149 is about this issue

**Comment by laxersaz** [comment]
Reopened since this is about the sources of the __feature__ files and #149 is about the __json__ files

**Comment by bischoffdev** [comment]
This is visible in the tree view page.
