### ISSUE TITLE
In 'All Scenarios' page (index.html), is it possible to have a collapse\expand option for the status sections?

### ISSUE THREAD

**Issue by bischoffdev** [trivago/cluecumber#175]
In 'All Scenarios' page (index.html), is it possible to have a collapse\expand option for the status sections (failed, skipped, passed). Saves effort of scrolling if there are multiple failures or skips to get to other sections below them.

_Originally posted by @grasshopper7 in https://github.com/trivago/cluecumber-report-plugin/issues/172#issuecomment-502475281_

**Comment by laxersaz** [comment]
If you click on the diagram headers, the according status sections are shown/hidden. Does this qualify as a solution?

![image](https://user-images.githubusercontent.com/5775857/59691436-4dc6f900-91e3-11e9-9fdb-175909de602c.png)

**Comment by grasshopper7** [comment]
Nice... That works for me. Only thing is that it is not intuitive. I clicked on the section headers and the portions of the pie chart but did not try the legend. Someway to indicate this functionality would be great.

In the 'Scenario Sequence' page I was expecting that when I click to hide the 'Passed' scenario in the pie chart it will also remove the 'Passed' scenario lines in the sequence table below. Is it a fair assumption?

**Comment by laxersaz** [comment]
I understand that it is not too consistent. I will keep this open and keep it in mind for the furtherdevelopment.

**Comment by jaskaran0001** [comment]
@laxersaz  Can we also have collapsable screenshots inside reports as for bigger workflows it becomes too long to traverse?
