### ISSUE TITLE
Clickable bars in bar chart for features, tags, steps summary

### ISSUE THREAD

**Issue by grasshopper7** [trivago/cluecumber#179]
Can the bars in features, tags, steps summary pages be made clickable so the link opens to the details page directly.
So it goes from pages/tag-summary.html to pages/tag-scenarios/tag_TagOver.html when the TagOver bar is clicked.
Saves the time for scrolling and searching for the desired tag, feature or step in the section below.

**Comment by laxersaz** [comment]
I will try this for the next release. It might be very tricky with the current chart library...

**Comment by laxersaz** [comment]
This is much harder than I thought. This needs further research.

**Comment by bischoffdev** [comment]
Ready to be released in v3.3.0
