### ISSUE TITLE
Option to show/hide hooks for each step independent of other steps

### ISSUE THREAD

**Issue by josepj** [trivago/cluecumber#186]
In my tests I use scenario.write() to write custom messages to the report, which I have found useful when debugging failed tests. When debugging a failed test with a large number of steps, it would be nice to be able to Show/Hide individual step hooks as I am scrolling down the list of steps (I have `expandStepHooks` set to false due to the large number of steps).

In case the description is not clear,I have tried to mock up a step below.

**_Hide step hooks_**:

![image](https://user-images.githubusercontent.com/9464895/60379140-17fbee80-99f3-11e9-8dc7-ca1e46b7126d.png)

**_Show step hooks_**:

![image](https://user-images.githubusercontent.com/9464895/60379144-2b0ebe80-99f3-11e9-9850-0db491808182.png)

**Comment by laxersaz** [comment]
Hi @josepj 
Thanks for this suggestion.
I will see if I can integrate something like this for the future releases.

**Comment by laxersaz** [comment]
Hi @josepj 
Thanks for this suggestion.
I will see if I can integrate something like this for the future releases.
