### ISSUE TITLE
Embedded content mimetype does not support charset

### ISSUE THREAD

**Issue by gzmrst** [trivago/cluecumber#205]
I embed HTML fragments in the scenarios to add meaningful info - showing the content of web service calls, etc., which works fine when I do 
`this.scenario.embed(htmlTextBytes, "text/html");` - all the attachments are properly added as html files and viewing the report in Chrome works as expected.
But when I try to add a charset to the mime type like
`this.scenario.embed(htmlTextBytes, "text/html; charset=utf-8");`
then the attachments are all created as '*.unknown' and the raw html code is shown in the report instead of the formatted html.
Some of my cucumber tests deal with international characters, so the charset is necessary for the characters to display properly.

**Comment by laxersaz** [comment]
Hi @gzmrst ,

I wasn't aware that this is even possible to add a charset to the mime type. Is this an officially documented feature?
If so, I will for sure include this.

Best,
Benjamin (laxersaz)

**Comment by laxersaz** [comment]
Yes, I am aware of this. However, I was wondering about Cucumber. I just posted this question to the Cucumber OSS group.

**Comment by laxersaz** [comment]
https://tools.ietf.org/html/rfc2045#section-5.1

**Comment by laxersaz** [comment]
I will add this to the next release, thanks for reporting, @gzmrst !

**Comment by bischoffdev** [comment]
Will have to get back to this as it is not that trivial with the current Cluecumber implementation.
