### ISSUE TITLE
Add error message to scenario overview pages

### ISSUE THREAD

**Issue by bischoffdev** [trivago/cluecumber#291]
At the moment, only the error class is shown.

**Comment by Jtejero11** [comment]
Following this thread

**Comment by bischoffdev** [comment]
I just released 2.9.1 that should do what you need.

**Comment by Jtejero11** [comment]
Hello Benjamin, everything works perfect. I have a question, would it be possible to print the error message in red? It seems to me that it is not quickly appreciated that this is an error message, is it something I can do myself?

**Comment by bischoffdev** [comment]
I tried it in red but this is pretty distracting from the other information in the failed scenario list. 
You can override parts of the css using a custom css file as described here:
https://github.com/trivago/cluecumber-report-plugin#defining-a-custom-css-file
