### ISSUE TITLE
v 3.0.1 does not show Exception if thrown in step below "Given"

### ISSUE THREAD

**Issue by OxygeneIV** [trivago/cluecumber#302]
v 3.0.1 does not show Exception if Assert is triggered in step below "Given"

If we set an assertion in a step below the "Given" step the assertion is not shown in the report.
I do get the Exception message if the Assert is made within the Given - step.

v 3.0.0:
![image](https://user-images.githubusercontent.com/2960057/208792207-413109c0-eaed-41ab-a873-c2e504f92c62.png)

v 3.0.1:
![image](https://user-images.githubusercontent.com/2960057/208792281-327874ef-574f-4a28-99f6-9e1f6b198692.png)

Assertion set in Step 3

![image](https://user-images.githubusercontent.com/2960057/208792364-a3bb963d-6a1c-4506-bb9d-44e990d4f757.png)

**Comment by bischoffdev** [comment]
Hello, thanks for the report! This is very helpful.
Could you please attach an example JSON for your case?

**Comment by OxygeneIV** [comment]
[cucumber_301.json.txt](https://github.com/trivago/cluecumber/files/10276346/cucumber_301.json.txt)

**Comment by bischoffdev** [comment]
Will look into it in a moment.

**Comment by bischoffdev** [comment]
Fixing now...

**Comment by bischoffdev** [comment]
Fixed in v3.0.2
