### ISSUE TITLE
PDF Format of Repor

### ISSUE THREAD

**Issue by testing-blaze** [trivago/cluecumber#306]
**Is your feature request related to a problem? Please describe.**
As the current report is generated in html and with multiple folder which makes it harder to share it after zipping. the audiance also prefer have a single pdf file as replor.

**Describe the solution you'd like**
Conversion or generation of PDF version of the html report.

**Comment by testing-blaze** [comment]
This is more like a question from you to see any possiblity.

**Comment by bischoffdev** [comment]
Cluecumber is meant to be an HTML reporting library so PDF support is not planned as of now. You can probably use command line tools in your pipeline to achieve that, e.g. [wkhtmltopdf](https://wkhtmltopdf.org/)
