### ISSUE TITLE
Pie chart always showing results from all features

### ISSUE THREAD

**Issue by d4vke** [trivago/cluecumber#311]
When clicking the "All scenarios" link, you can see a pie chart with the status of all features (x passed, x failed,...).
When drilling down to a feature, the same pie chart is shown, this was not the case in older versions.

This can be reproduced with the demo you have made available:
http://cluecumber.softwaretester.blog/pages/scenario-summary.html 

In version 2.5.0 you saw the pie chart with the status of the scenarios of a specific feature.

I noticed this  behaviour change when updating the plugin from version 2.5.0 to version 2.9.3.

**Comment by bischoffdev** [comment]
Thanks for spotting this, I will try to do a bugfix release by tomorrow.

**Comment by bischoffdev** [comment]
Fixed and release 😏
