### ISSUE TITLE
Inconsistent Background handling

### ISSUE THREAD

**Issue by bischoffdev** [trivago/cluecumber#319]
**Describe the bug**
Failure in Background steps followed by skipped steps ist considered skipped instead of failed.

**Comment by mpkorstanje** [comment]
@bischoffdev I saw the code that determines the outcome, you can simplify it a lot.

For all steps in a scenario (background, hooks, regular steps, ect), put them in a list. Then find find the worst status. That's the outcome of the scenario.

**Comment by bischoffdev** [comment]
Yes doing this now. I noticed that I never handled Background steps correctly at all.

**Comment by bischoffdev** [comment]
Ready for release in 3.4.0
