### ISSUE TITLE
The iFrame element shows empty content under HTML attachment Scenario Step 

### ISSUE THREAD

**Issue by matlaria90** [trivago/cluecumber#321]
When I upload the html report on cloud bucket and I try to open it using Chrome or Firefox browser, the iFrame element doesn't show content inside the HTML attachment section.
If I open the DOM I am able to find the content inside the iFrame element.

**To Reproduce**
1. Generate a html report using "Cluecumber Core" with version 3.4.0
2. Upload the html report folders on cloud bucket
3. Go to link related of one specific test case
4. Scroll down to step that contains the "toggle" table
5. Expand the table clicking on "toggle" link
6. The iFrame is empty

**Expected behavior**
I should see the html content inside the "toggle" section

**Attachments**
![image](https://github.com/trivago/cluecumber/assets/44551336/306f5d26-f78f-4ddb-861d-bd9c6fa83d65)

![image](https://github.com/trivago/cluecumber/assets/44551336/ab500e67-1c62-41df-a44e-1797a948a96e)

**Additional context**
Seems that the issue could be the attribute "height" inside the iFrame element that is set to 1 like default.
If I try to perform a force change to "100%", I am able to see the content of the html attachement (in any case the view is not beautiful since that I should scroll down in order to see all the content)

**Comment by bischoffdev** [comment]
Hello and thanks for reporting!
Could you please attach a sample JSON result that demos this behavior? That would make it easier to test.

**Comment by matlaria90** [comment]
Hello @bischoffdev ,

I attached an example of json file [cucumber.zip](https://github.com/trivago/cluecumber/files/12829405/cucumber.zip)
Meanwhile I fixed this issue using a workaround. I used a custom css in which I specified that the "iframe" element should have a fix dimention.

`iframe {
  height: 800px;
}`

**Comment by bischoffdev** [comment]
I will check this next week, thanks for the example!

**Comment by bischoffdev** [comment]
I checked your example and it works fine for Firefox and Chrome. When toggling the attachments, it shows the full iFrame content for me.

Firefox:
![image](https://github.com/trivago/cluecumber/assets/5775857/ef67a2f4-40f6-4924-b91e-7e75f2f62d63)

Chrome:
![image](https://github.com/trivago/cluecumber/assets/5775857/72d5f38f-c280-45c7-822f-f87c88ef104b)

The iFrame height is set correctly via JS.

Which browser and OS are you using?

**Comment by matlaria90** [comment]
Hello @bischoffdev, 
we investigated on the issue and seems that there is a "DOMException" when we try to open the html report directly on Sonatype Nexus application.
![d3](https://github.com/trivago/cluecumber/assets/44551336/27c61d43-e86b-46b1-9492-fc9db1bac435)

We solved using a custom css that we decide to use only in some specific cases (in this way we avoid to use a fix sizing for all the generated report)

`iframe {
  height: 800px;
}`

**Comment by matlaria90** [comment]
I think that we can close this defect for the moment becasue could be a issue that rarely happens and the workaround is easy to manage.
