### ISSUE TITLE
Improve the filtering of "Search" fields

### ISSUE THREAD

**Issue by matlaria90** [trivago/cluecumber#328]
**Topic** 

The QA team members asked us to improve the filter actions provided by "Search" fields present into the html report.
In the specific, they wanted to filter the failures test cases using the values prensent inside each column of the report section.

For example the image below show you the scenario failures for a specific execution and using th search field, the QA would want to filter using the name of the colulmn (feature, scenario, started) and some combinations.

e.g. They suggested us to adopt the same solution used on Jira Atlassian in order to filter its components :

_feature ~ "NRT light" AND scenario not in ("GN-031", "GN-034")_

based on this example, the result should display only the line that have a GN code different from 031 and 034 and releted to feature fils "NRT light"

![image](https://github.com/trivago/cluecumber/assets/44551336/68d98b02-d094-460c-b338-0daf425128e2)

**Comment by bischoffdev** [comment]
Interesting idea. However, this also sounds like something that could be achieved with tags as well. Also you can click on the feature to open the page that lists all scenarios in this feature and then use the search box.
I will keep this feature in mind for a future iteration.

**Comment by bischoffdev** [comment]
The table component that is used for Cluecumber does not support using a custom search DSL.
