### ISSUE TITLE
Upload 3+ releases to Maven Central

### ISSUE THREAD

**Issue by martin-kosmos** [trivago/cluecumber#339]
Hey guys,
Thanks a lot for this awesome plugin which we use everyday in my company.

I was just wondering if you could upload recent releases to Maven Central, because I would enjoy a lot trying out version 3+.
Keep up the great work.

Cheers,
Martin

**Comment by mpkorstanje** [comment]
I suspect you've missed this entry in the changelog:

https://github.com/trivago/cluecumber/blob/main/CHANGELOG.md#300---2022-12-03

**Comment by martin-kosmos** [comment]
You're absolutely right, I missed this. Thanks!

I clicked on the "Maven Central" link on the documentation. Maybe it could be updated to show all versions (like [this](https://central.sonatype.com/search?q=g%3Acom.trivago.rta++a%3Acluecumber-core+a%3Acluecumber-engine+a%3Acluecumber-maven&smo=true)).

**Comment by bischoffdev** [comment]
I updated the Maven banner link now as suggested.
