### ISSUE TITLE
Possibility to easily define a favicon to all report web pages

### ISSUE THREAD

**Issue by NicoIodice** [trivago/cluecumber#340]
**Is your feature request related to a problem? Please describe.**
I have tried different solutions to automatically add a favicon on all web pages of the Cluecumber report but without success. Still did not find a easy way to do it.

**Describe the solution you'd like**
Maybe use the web pages ftl templates to include this toggle and making it easy, using the pom configurations, to add a favicon to the report to be displayed on the browser.

**Describe alternatives you've considered**
I've considered using css, javascript and injecting the info on all web pages (not feasible though)

**Additional context**
This is a low feature request.
![2024-03-26_18h26_19](https://github.com/trivago/cluecumber/assets/136837100/acb854a8-6328-44af-a105-98827974e240)

**Comment by bischoffdev** [comment]
Good idea, will consider this for the next release.

**Comment by AkshayChavanVerint** [comment]
@bischoffdev I am also interested in this feature to improve look of report. Please share when this will be released

**Comment by bischoffdev** [comment]
Ready for release

**Comment by NicoIodice** [comment]
Hi @bischoffdev. Thank you very much. I've just included this in our report and it works fine :)

**Comment by bischoffdev** [comment]
Great to hear, thanks for the feedback!
