### ISSUE TITLE
Don't show failures of previous runs in the graphs unless expanded

### ISSUE THREAD

**Issue by bischoffdev** [trivago/cluecumber#344]
# Scenario Summary

- [x] Show only passed, fail & skipped without reruns
- [x] Show additional rerun info (passed, failed, skipped)?
- [x] Scenarios with prior reruns should be marked in the scenario summary table nonetheless

# Rerun page

- [x] Reruns should be collectively shown on a dedicated page instead of scattered in the "regular" runs
- [x] Show data and graph for reruns only

# Scenario sequence

- [x]  Reruns should be marked here

# All tags / All steps / All features

- [x] Reruns should not be counted here

# Tree view

- [x] No changes necessary

# Scenario pages

- [x] Re-implement page rendering for multi run children
- [x] Fix links from report pages to multi run children sub pages

**Comment by AkshayChavanVerint** [comment]
@bischoffdev Any timelines for 3.8.0 release, This will help a lot to avoid confusion with false reporting

**Comment by bischoffdev** [comment]
Hello, I have some other development tasks at the moment so this will take some more time for sure. Maybe at the end of next week could be achievable.

**Comment by bischoffdev** [comment]
Started major refactoring of data processing since it is needed for these features.
