### ISSUE TITLE
Test scenario is marked as 'Skipped' instead of 'Failed' when flag to 'failScenariosOnPendingOrUndefinedSteps' is enabled

### ISSUE THREAD

**Issue by NicoIodice** [trivago/cluecumber#347]
**Describe the bug**
Test scenario is marked as *Skipped* instead of *Failed* when flag to *failScenariosOnPendingOrUndefinedSteps* is enabled

**To Reproduce**
1. Enable the flag on the pom configuration section
```
<failScenariosOnPendingOrUndefinedSteps>true</failScenariosOnPendingOrUndefinedSteps>
```
2. Execute a cucumber test scenario with and undefined step
3. Generate the report
4. Open the report generated on the previous step

**Expected behavior**
Test scenario should be marked as *Failed* and should be displayed on that report section

**Actual behavior**
Test scenario is marked as *Skipped* and is displaued on that report section

**Attachments**
![2024-07-12_11h50_13](https://github.com/user-attachments/assets/4641f1a5-d1ff-44c6-b765-1a28745aabe0)

Maven logs:
```
[ERROR] Feature1.Feature1 - Test Scenario Name -- Time elapsed: 43.79 s <<< ERROR!
io.cucumber.junit.platform.engine.UndefinedStepException: 
The step 'Search for client "Test client"' is undefined.
You can implement this step using the snippet(s) below:

@Then("Search for client {string}")
public void search_for_client(String string) {
    // Write code here that turns the phrase above into concrete actions
    throw new io.cucumber.java.PendingException();
}
```

**Additional context**
I remember this feature was working as expected on previous versions.

**Comment by bischoffdev** [comment]
Checking this, thanks for reporting

**Comment by bischoffdev** [comment]
I can reproduce this, fixing is in progress

**Comment by bischoffdev** [comment]
Released in `3.7.1`

**Comment by NicoIodice** [comment]
Thank you. Tested and is resolved :)

![cluecumber_solved](https://github.com/user-attachments/assets/f52952ad-09db-463c-889d-f53e0829a0f3)

**Comment by bischoffdev** [comment]
Perfect, thanks for your confirmation!
