### ISSUE TITLE
Generate Reports Should Accepts Multiple json files

### ISSUE THREAD

**Issue by chik145** [trivago/cluecumber#349]
**Is your feature request related to a problem? Please describe.**
In case of multiple json files, we need to merge them & build a single report.

**Describe the solution you'd like**
please create another function of generateReports(List<String> jsonDirectory, String reportDirectory)

**Describe alternatives you've considered**
please create another function of generateReports(String [] jsonDirectory, String reportDirectory)

**Comment by bischoffdev** [comment]
You don't need to merge multiple JSON files. By specifying a directory, Cluecumber already crawls all sub directories and included JSON files and combines them into a report.
