### ISSUE TITLE
single-file html generation

### ISSUE THREAD

**Issue by sadiqkassamali** [trivago/cluecumber#350]
looking for a way to generate single file html, so we dont have the zip around the folder with data.

Generate single HTML file after test are completed.

Allure as something similar with allure generate --single-file

**Comment by bischoffdev** [comment]
No sorry, this is not planned as this would mean changing the core Cluecumber engine completely.

**Comment by sadiqkassamali** [comment]
even if it's not planned, can you have it opened might come handy later

**Comment by bischoffdev** [comment]
Sorry no, this is not something that will happen with Cluecumber. Its architecture only allows a multi-page report setup. Also, having hundreds or even thousands of test cases along with attachments, docstrings and outputs in a single file would not make sense size and performance wise. So if the single page is something you require, then Cluecumber is probably not feasible for you.

**Comment by sadiqkassamali** [comment]
Ty and make sense... great project
