### ISSUE TITLE
Allow report generation even if <customParametersFile> defined file does not exist

### ISSUE THREAD

**Issue by NicoIodice** [trivago/cluecumber#357]
**Is your feature request related to a problem? Please describe.**
With <customParametersFile> we can define a file to customize the final report. This file should exist for the cluecumber plugin to generate the report. In our case,  resource.properties file content is dynamically generated with a custom tool, thus the file should exist on git. When there are errors generating the properties file, the cluecumber report is not created. Is it possible to allow the generation of the cluebumer report even if this file does not exist?

**Describe the solution you'd like**
Throw a warning for the user to easily identify that something is wrong with the resource.properties file defined in the <customParametersFile>, either for file not existent, or bad format, etc

**Describe alternatives you've considered**
I've created the file in gitlab with no content and untracked it so my IDEA stops identifying this auto-generated file to commit and push. This is just a trivial nice-to-have feature :)

**Additional context**
`[ERROR] Failed to execute goal com.trivago.rta:cluecumber-maven:3.8.1:reporting (default-cli) on project automation-tests-reports: File '/builds/cgdpnce/pemp/cgd-corporateloans-e2e-automation-tests/automation-tests-reports/src/test/resources/report.properties (customParametersFile)' could not be found. -> [Help 1]`

**Comment by bischoffdev** [comment]
This can be included in the next release.

**Comment by bischoffdev** [comment]
Ready for release in 3.8.3

**Comment by bischoffdev** [comment]
Released

**Comment by NicoIodice** [comment]
Thank you. Will update it :)
