### ISSUE TITLE
Plugin doesn't support parallel compilation

### ISSUE THREAD

**Issue by henri-tremblay** [trivago/cluecumber#358]
**Is your feature request related to a problem? Please describe.**

We want to build using Maven param 1.0C. But this plugin doesn't support threading.

**Describe the solution you'd like**

If it does support threading, the goal should be annotated to mention it. If not, the code should be fixed to support it. Since we have seen the plugin crash in parallel, some code needs to be fixed.

**Describe alternatives you've considered**

Run the report in a separate build that doesn't run in parall.

**Additional context**

Tested on 2.9.4 with -T 1.0C and about 12 modules. Java 21 and Maven 3.9.9.

**Comment by bischoffdev** [comment]
Version `2.9.4` is quite outdated. The newest one is `3.8.1`. Have you tried it with this one?

**Comment by henri-tremblay** [comment]
Indeed. I missed that the plugin was renamed. But trying with 3.8.1. However, you still have the threading warning. If it's supported, you should do `@Mojo(name = "reporting", requiresProject = false, threadSafe = true)`. Looking quickly at the code in the mojo, it seems fine.

**Comment by bischoffdev** [comment]
Implemented for 3.8.3

**Comment by bischoffdev** [comment]
Released

**Comment by henri-tremblay** [comment]
Thanks!
