### ISSUE TITLE
Merging of reports with same test scenario doesn't work when output is different

### ISSUE THREAD

**Issue by Shendor** [trivago/cluecumber#359]
**Describe the bug**
When I supply 2 Cucumber json report files to `CluecumberEngine` with `CluecumberCore.Builder.setGroupPreviousScenarioRuns(true)`
it doesn't merge the same test scenarios (rerun) which have test steps with different outputs. In my case, each test step has a log attached so, obviously, it will be different when I rerun, for example, a failed test scenario.

**To Reproduce**
1. Have 2 Cucumber json reports for the same features but run different time and where test steps have different output
2. Set the flag CluecumberCore.Builder.setGroupPreviousScenarioRuns(true)
3. Call `CluecumberEngine.generateReports` 
4. Open html report and see it treats same test scenarios as different

**Expected behavior**
Rerun test scenarios with same name of the same features and same test data should be displayed as test scenarios which were rerun (in `Rerun Scenarios` page)

**Attachments**
Nothing is displayed in page `Rerun Scenarios` of the Cluecumber html report

**Additional context**
Based on the code, I see that `ElementMultipleRunsPreProcessor.generateCombinedId` method uses this:
```java
 if (step.getOutput() != null) {
                outputs.add(step.getOutput());
            }
```
which, to my mind, should not be in the resulted ID generation, as you may have the same test scenarios but different log outputs after rerun.
Can we change this logic please?
Possible options:
1) Remove this piece of code
2) Wrap it around a configuration, supplied from the `CluecumberEngine` and its Builder
What do you think?

**Comment by bischoffdev** [comment]
Will look into this, thanks for reporting.

**Comment by bischoffdev** [comment]
Ready for release in 3.8.3

**Comment by bischoffdev** [comment]
Released

**Comment by Shendor** [comment]
Thanks @bischoffdev, I'll check that version.
